name: SlimefunRecipeManager
version: '${project.version}'
main: me.char321.sfrecipes.RecipePlugin
api-version: 1.14
depend: [ Slimefun ]
description: A Slimefun Addon that allows you to adjust recipes. 

commands:
  genrecipes:
    description: creates default recipes in recipes.yml and adds items to itemstacks.yml as needed
  reload:
    description: applies recipes in recipes.yml
